version: "3.9"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quibit

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health_check" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes: # fixme
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  rq:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: rq worker --with-scheduler --url redis://redis:6379
    restart: on-failure
    volumes: # fixme
      - ./backend:/app
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend