version: "3.9"

services:
  redis:
    image: redis:latest

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quibit

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health_check" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes: # fixme
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - db

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery --app=app.worker.celery worker --loglevel=info
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend